### PR TITLE
Add debug logging & mode toggle example.

### PR DESCRIPTION
**Pull request by piotrbulinski**

### CODE REVIEW

**Comment by piotrbulinski** [comment]
@lellky can you please run the new example/change_mode.py with this command:
```
DEBUG=1 PYTHONPATH=. python3 examples/change_mode.py <ip-address>
```
and post here the output here?

**Comment by lellky** [comment]
Sure thing!

```
(venv) lellky@Jonass-MacBook-Air flexit_bacnet % DEBUG=1 PYTHONPATH=. python3 examples/change_mode.py 192.168.2.14
>>> 810a01a101040244010e0c014000321e09551f0c0c00013e1e09551f0c04c001691e09551f0c04c0002a1e09551f0c008007c11e09551f0c008007ca1e09551f0c04c001681e09551f0c0c00010e1e09551f0c008007f61e09551f0c04c001651e09551f0c0c0001251e09551f0c008007ef1e09551f0c000000011e09551f0c000000041e09551f0c000000051e09551f0c0000000b1e09551f0c0000000c1e09551f0c0000003b1e09551f0c0000004b1e09551f0c004000031e09551f0c004000041e09551f0c004000001e09551f0c008007e71e09551f0c014001bd1e09551f0c008000be1e09551f0c008000c21e09551f0c014001921e09551f0c0080072b1e09551f0c0080072c1e09551f0c0080072d1e09551f0c0080072e1e09551f0c0080072f1e09551f0c008007301e09551f0c008007311e09551f0c008007321e09551f0c008007331e09551f0c008007341e09551f0c0080011d1e09551f0c0080011e1e09551f0c0140020a1e09551f0c04c002651e09551f0c0080082d1e09551f0c0080082e1e09551f0c0080082f1e09551f0c020000021e094d091c1f
<<< 810a02d1010030010e0c014000321e29554e91014f1f0c0c00013e1e29554e21004f1f0c04c001691e29554e21034f1f0c04c0002a1e29554e21034f1f0c008007c11e29554e44419000004f1f0c008007ca1e29554e4441a800004f1f0c04c001681e29554e21014f1f0c0c00010e1e29554e210a4f1f0c008007f61e29554e44412000004f1f0c04c001651e29554e21014f1f0c0c0001251e29554e211e4f1f0c008007ef1e29554e4441f000004f1f0c000000011e29554e44bf3d70a44f1f0c000000041e29554e44417c51ec4f1f0c000000051e29554e44453120004f1f0c0000000b1e29554e44407ae1484f1f0c0000000c1e29554e44452520004f1f0c0000003b1e29554e44419bc28f4f1f0c0000004b1e29554e44417851ec4f1f0c004000031e29554e44429400004f1f0c004000041e29554e44428c00004f1f0c004000001e29554e4442c800004f1f0c008007e71e29554e444299e25c4f1f0c014001bd1e29554e91004f1f0c008000be1e29554e443f4ccccd4f1f0c008000c21e29554e44000000004f1f0c014001921e29554e91004f1f0c0080072b1e29554e4442c800004f1f0c0080072c1e29554e44429400004f1f0c0080072d1e29554e44422800004f1f0c0080072e1e29554e4442b400004f1f0c0080072f1e29554e44424800004f1f0c008007301e29554e4442c800004f1f0c008007311e29554e44428c00004f1f0c008007321e29554e44422000004f1f0c008007331e29554e44424800004f1f0c008007341e29554e44424800004f1f0c0080011d1e29554e4443e200004f1f0c0080011e1e29554e44460940004f1f0c0140020a1e29554e91004f1f0c04c002651e29554e21014f1f0c0080082d1e29555e9101911f5f1f0c0080082e1e29555e9101911f5f1f0c0080082f1e29555e9101911f5f1f0c020000021e294d4e750e0048766163466e63743231795f414f291c4e750e003830303133302d3030323936374f1f
Comfort button: 1
Operation mode: Home
Ventilation mode (before): Home
>>> 810a01a101040244010e0c014000321e09551f0c0c00013e1e09551f0c04c001691e09551f0c04c0002a1e09551f0c008007c11e09551f0c008007ca1e09551f0c04c001681e09551f0c0c00010e1e09551f0c008007f61e09551f0c04c001651e09551f0c0c0001251e09551f0c008007ef1e09551f0c000000011e09551f0c000000041e09551f0c000000051e09551f0c0000000b1e09551f0c0000000c1e09551f0c0000003b1e09551f0c0000004b1e09551f0c004000031e09551f0c004000041e09551f0c004000001e09551f0c008007e71e09551f0c014001bd1e09551f0c008000be1e09551f0c008000c21e09551f0c014001921e09551f0c0080072b1e09551f0c0080072c1e09551f0c0080072d1e09551f0c0080072e1e09551f0c0080072f1e09551f0c008007301e09551f0c008007311e09551f0c008007321e09551f0c008007331e09551f0c008007341e09551f0c0080011d1e09551f0c0080011e1e09551f0c0140020a1e09551f0c04c002651e09551f0c0080082d1e09551f0c0080082e1e09551f0c0080082f1e09551f0c020000021e094d091c1f
<<< 810a02d1010030010e0c014000321e29554e91014f1f0c0c00013e1e29554e21004f1f0c04c001691e29554e21024f1f0c04c0002a1e29554e21024f1f0c008007c11e29554e44419000004f1f0c008007ca1e29554e4441a800004f1f0c04c001681e29554e21014f1f0c0c00010e1e29554e210a4f1f0c008007f61e29554e44412000004f1f0c04c001651e29554e21014f1f0c0c0001251e29554e211e4f1f0c008007ef1e29554e4441f000004f1f0c000000011e29554e44bf3d70a44f1f0c000000041e29554e44417c51ec4f1f0c000000051e29554e44453120004f1f0c0000000b1e29554e44407ae1484f1f0c0000000c1e29554e44452520004f1f0c0000003b1e29554e44419bc28f4f1f0c0000004b1e29554e44417851ec4f1f0c004000031e29554e44429400004f1f0c004000041e29554e44428c00004f1f0c004000001e29554e4442c800004f1f0c008007e71e29554e444299e25c4f1f0c014001bd1e29554e91004f1f0c008000be1e29554e443f4ccccd4f1f0c008000c21e29554e44000000004f1f0c014001921e29554e91004f1f0c0080072b1e29554e4442c800004f1f0c0080072c1e29554e44429400004f1f0c0080072d1e29554e44422800004f1f0c0080072e1e29554e4442b400004f1f0c0080072f1e29554e44424800004f1f0c008007301e29554e4442c800004f1f0c008007311e29554e44428c00004f1f0c008007321e29554e44422000004f1f0c008007331e29554e44424800004f1f0c008007341e29554e44424800004f1f0c0080011d1e29554e4443e200004f1f0c0080011e1e29554e44460940004f1f0c0140020a1e29554e91004f1f0c04c002651e29554e21014f1f0c0080082d1e29555e9101911f5f1f0c0080082e1e29555e9101911f5f1f0c0080082f1e29555e9101911f5f1f0c020000021e294d4e750e0048766163466e63743231795f414f291c4e750e003830303133302d3030323936374f1f
Ventilation mode (after):  Away
```

It seems to work now! 🎉

**Comment by lellky** [comment]
I don't understand why it did not work before, but now all the examples work as intended!

**Review by lellky — APPROVED** [review]

**Comment by piotrbulinski** [comment]
@lellky I think I know what the problem was. Since there was no error, I suspect that you had your unit running in "away" mode through the comfort button. See comment https://github.com/piotrbulinski/flexit_bacnet/blob/main/flexit_bacnet/nordic.py#L7 explaining this a bit more - it's based on info from https://www.flexit.no/globalassets/catalog/documents/bacnet-nordic-basic_2963.xlsx:

> Comfort button
> 0 = Ventilation mode Away after Away delay timer duration [Pintval,318]. Also overrides Room operating mode [Mval,42].
> 1 = Ventilation mode according to Room operating mode [Mval,42].

So whenever you toggle the comfort button to Away mode, changing of the ventilation mode will not show any changes until comfort button is active. I was surprised by it myself when I was working on the first version of this library.

**Comment by lellky** [comment]
That is weird. I don't know anything about a "comfort button". Maybe the app does something fishy. I toggle between Home and Away mode using the app like this:
Screenshot_20230201-184531

**Pull request merged**
